"""Bounded client HTTP transport, isolated so DNS and header reads can be stopped."""
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

import requests


RESPONSE_LIMIT = 1024 * 1024
NETWORK_ERROR = 'Client is unreachable. Check its address, service, and network access.'


def proxy_request(method, url, token, payload, read_timeout):
    from .image_updates import run_bounded

    request = dict(method=method, url=url, token=token, payload=payload, read_timeout=read_timeout)
    env = {key: value for key, value in os.environ.items() if not key.upper().startswith('ORCA_')}
    # A file-backed stdin keeps credentials out of command arguments and avoids
    # pipe write deadlocks. TemporaryFile is private and unlinked on POSIX.
    with tempfile.TemporaryFile(mode='w+b') as input_file:
        input_file.write(json.dumps(request).encode('utf-8'))
        input_file.seek(0)
        try:
            result = run_bounded([sys.executable, '-I', str(Path(__file__).resolve()), '--worker'],
                                 timeout=read_timeout + 5, max_output=4 * RESPONSE_LIMIT,
                                 env=env, stdin=input_file)
        except subprocess.TimeoutExpired:
            raise RuntimeError('Client response exceeded its time limit.') from None
        except (OSError, subprocess.SubprocessError, RuntimeError):
            raise RuntimeError(NETWORK_ERROR) from None
    if result.returncode:
        raise RuntimeError(NETWORK_ERROR)
    try:
        response = json.loads(result.stdout)
        if response.get('error'):
            # Errors are generated by the static worker, never remote response text.
            raise RuntimeError(response['error'])
        return response['value'], response['status']
    except (ValueError, TypeError, KeyError, AttributeError, RecursionError):
        raise RuntimeError('Client returned an invalid response.') from None


def _request(data):
    with requests.Session() as transport:
        transport.trust_env = False
        with transport.request(data['method'], data['url'],
                               headers={'Authorization': 'Bearer ' + data['token']},
                               json=data['payload'], timeout=(3, data['read_timeout']),
                               allow_redirects=False, stream=True) as response:
            if 300 <= response.status_code < 400:
                raise RuntimeError('Client redirected the request. Check its configured address.')
            if response.status_code in (401, 403):
                raise RuntimeError('Client authentication failed. Check the saved client token.')
            if not 200 <= response.status_code <= 599:
                raise RuntimeError('Client returned an invalid response.')
            content = bytearray()
            for chunk in response.iter_content(16384):
                content.extend(chunk)
                if len(content) > RESPONSE_LIMIT:
                    raise RuntimeError('Client response exceeded the size limit.')
            try:
                value = json.loads(content)
            except (ValueError, UnicodeError, RecursionError):
                raise RuntimeError('Client returned an invalid response.') from None
            return dict(value=value, status=response.status_code)


def _worker():
    try:
        data = json.load(sys.stdin.buffer)
        result = _request(data)
    except requests.RequestException:
        result = dict(error=NETWORK_ERROR)
    except RuntimeError as error:
        result = dict(error=str(error))
    except Exception:
        result = dict(error='Client returned an invalid response.')
    # ASCII encoding keeps the response bound predictable for arbitrary Unicode.
    print(json.dumps(result, ensure_ascii=True))


if __name__ == '__main__':
    _worker()
