const {chromium}=require(process.env.ORCA_PLAYWRIGHT || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true, executablePath:process.env.ORCA_BROWSER || undefined});
 const page=await browser.newPage({viewport:{width:1280,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');
 await page.getByRole('heading',{name:'Your home base'}).waitFor();
 assert.equal(await page.locator('#fleet').isVisible(),false);
 await page.getByRole('button',{name:'Admin login',exact:true}).click();
 await page.getByLabel('Password',{exact:true}).fill('orca-preview-local');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('heading',{name:'Your fleet'}).waitFor();
 await page.getByRole('button',{name:'+ Add action',exact:true}).waitFor();
 await page.getByRole('button',{name:'+ Add client',exact:true}).click();
 await page.getByRole('button',{name:'+ Add client',exact:true}).click();
 assert.equal(await page.locator('#client-editor').isVisible(),true);
 await page.locator('#client-editor').getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'+ Add shortcut',exact:true}).click();
 await page.locator('#shortcut-editor').getByLabel('Name',{exact:true}).fill('Shared link');
 await page.locator('#shortcut-editor').getByLabel('URL',{exact:true}).fill('https://example.com');
 await page.locator('#shortcut-editor').getByLabel('Visibility').selectOption('shared');
 await page.getByRole('button',{name:'Save shortcut',exact:true}).click();
 await page.getByRole('link',{name:'Shared link'}).waitFor();
 await page.getByRole('button',{name:'+ Add shortcut',exact:true}).click();
 await page.locator('#shortcut-editor').getByLabel('Name',{exact:true}).fill('Private link');
 await page.locator('#shortcut-editor').getByLabel('URL',{exact:true}).fill('https://example.com/private');
 await page.getByRole('button',{name:'Save shortcut',exact:true}).click();
 await page.getByRole('link',{name:'Private link'}).waitFor();
 await page.getByRole('button',{name:'+ Add action',exact:true}).click();
 await page.locator('#action-editor').getByLabel('Name',{exact:true}).fill('Connection test');
 await page.locator('#action-editor').getByLabel('Command',{exact:true}).fill('printf "Orca client connected successfully\\n"');
 await page.getByRole('button',{name:'Save action',exact:true}).click();
 await page.getByRole('button',{name:'Connection test',exact:true}).click();
 await page.getByRole('button',{name:'Run action',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#job-status').textContent==='succeeded');
 assert.match(await page.locator('#output').textContent(),/connected successfully/);
 await page.screenshot({path:'/tmp/orca-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'+ Add shortcut',exact:true}).click();
 const grid=await page.locator('#shortcuts').boundingBox(),form=await page.locator('#shortcut-editor').boundingBox();
 assert.ok(form.y>=grid.y+grid.height);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'/tmp/orca-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Shared view',exact:true}).click();
 await page.getByRole('heading',{name:'Your home base'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Private link'}).count(),0);
 assert.equal(await page.locator('#fleet-summary').isVisible(),false);
 assert.equal(await page.locator('#workspace').isVisible(),false);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByRole('button',{name:'Admin login',exact:true}).waitFor();
 await page.reload();
 await page.getByRole('link',{name:'Shared link'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Private link'}).count(),0);
 const clientPage=await browser.newPage();
 await clientPage.goto('http://127.0.0.1:8766');
 await clientPage.getByRole('button',{name:'Admin login',exact:true}).click();
 await clientPage.getByLabel('Password',{exact:true}).fill('orca-preview-local');
 await clientPage.getByRole('button',{name:'Sign in',exact:true}).click();
 await clientPage.getByRole('button',{name:'Connection test',exact:true}).waitFor();
 assert.match(await clientPage.locator('#output').textContent(),/connected successfully/);
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('Browser passed: login, independent client, real command output, persistence, private shortcuts, forms, and mobile layout.');
})().catch(e=>{console.error(e);process.exit(1)});
