const {chromium}=require(process.env.ORCA_PLAYWRIGHT || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true, executablePath:process.env.ORCA_BROWSER || undefined});
 const page=await browser.newPage({viewport:{width:1280,height:1000}});
 await page.route('https://example.com/favicon.ico',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><rect width="24" height="24" fill="teal"/></svg>'}));
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:'+(process.env.ORCA_PREVIEW_PORT || '8765'));
 await page.getByRole('heading',{name:'Your home base'}).waitFor();
 assert.equal(await page.locator('#fleet').isVisible(),false);
 await page.getByRole('button',{name:'Admin login',exact:true}).click();
 await page.getByLabel('Password',{exact:true}).fill('orca-preview-local');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('heading',{name:'Your fleet'}).waitFor();
 await page.locator('.server').first().waitFor();
 assert.equal(await page.locator('#workspace').isVisible(),false);
 assert.equal(await page.locator('.server.selected').count(),0);
 await page.reload();
 await page.locator('.server').first().waitFor();
 assert.equal(await page.locator('#workspace').isVisible(),false);
 assert.equal(await page.locator('.server.selected').count(),0);
 await page.locator('.server').first().click();
 assert.equal(await page.locator('#connection').count(),0);
 await page.getByRole('button',{name:'+ Add action',exact:true}).waitFor();
 await page.getByRole('button',{name:'+ Add client',exact:true}).click();
 await page.getByRole('button',{name:'+ Add client',exact:true}).click();
 assert.equal(await page.locator('#client-editor').isVisible(),true);
 let form=await page.locator('#client-editor').boundingBox(),items=await page.locator('#servers').boundingBox();
 assert.ok(form.y+form.height<=items.y);
 await page.locator('#client-editor').getByRole('button',{name:'Cancel',exact:true}).click();
 await page.locator('.server').first().click();
 await page.getByRole('button',{name:'+ Add action',exact:true}).waitFor();
 await page.getByRole('button',{name:'Edit Local test client',exact:true}).click();
 await page.locator('#client-editor').getByLabel('Name',{exact:true}).fill('Unsaved client name');
 assert.equal(await page.locator('#workspace').isVisible(),false);
 assert.equal(await page.locator('.server.selected').count(),0);
 assert.equal(await page.locator('#client-editor').isVisible(),true);
 assert.equal(await page.locator('#client-editor').getByLabel('Name',{exact:true}).inputValue(),'Unsaved client name');
 await page.locator('.server').first().click();
 assert.equal(await page.locator('#client-editor').isVisible(),false);
 await page.getByRole('button',{name:'+ Add action',exact:true}).waitFor();

 await page.getByRole('button',{name:'+ Add shortcut',exact:true}).click();
 form=await page.locator('#shortcut-editor').boundingBox();items=await page.locator('#shortcuts').boundingBox();
 assert.ok(form.y+form.height<=items.y);
 await page.locator('#shortcut-editor').getByLabel('Name',{exact:true}).fill('Shared link');
 await page.locator('#shortcut-editor').getByLabel('URL',{exact:true}).fill('https://example.com');
 await page.locator('#shortcut-editor').getByLabel('Visibility').selectOption('shared');
 await page.locator('#shortcut-editor').getByLabel('Open in').selectOption('same_tab');
 await page.getByRole('button',{name:'Save shortcut',exact:true}).click();
 await page.getByRole('link',{name:'Shared link'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Shared link',exact:true}).getAttribute('target'),'_self');
 assert.match(await page.getByRole('link',{name:'Shared link',exact:true}).textContent(),/Shared link - Shared.*https:\/\/example.com/);
 assert.equal(await page.locator('.shortcut img').first().getAttribute('src'),'https://example.com/favicon.ico');
 await page.locator('.shortcut img').first().dispatchEvent('error');
 assert.equal(await page.locator('.shortcut-icon > span').first().isVisible(),true);
 assert.equal(await page.locator('#notice').count(),0);
 assert.doesNotMatch(await page.locator('#client-address').textContent(),/Client manager|Host metrics| · Host/);
 await page.getByRole('button',{name:'+ Add shortcut',exact:true}).click();
 await page.locator('#shortcut-editor').getByLabel('Name',{exact:true}).fill('Private link');
 await page.locator('#shortcut-editor').getByLabel('URL',{exact:true}).fill('https://example.com/private');
 await page.getByRole('button',{name:'Save shortcut',exact:true}).click();
 await page.getByRole('link',{name:'Private link'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Private link',exact:true}).getAttribute('target'),'_blank');
 await page.getByRole('button',{name:'+ Add action',exact:true}).click();
 form=await page.locator('#action-editor').boundingBox();items=await page.locator('#actions').boundingBox();
 assert.ok(form.y+form.height<=items.y);
 await page.locator('#action-editor').getByLabel('Name',{exact:true}).fill('Connection test');
 await page.locator('#action-editor').getByLabel('Command',{exact:true}).fill('printf "Orca client connected successfully\\n"');
 await page.getByRole('button',{name:'Save action',exact:true}).click();
 await page.getByRole('button',{name:'Information about Connection test',exact:true}).click();
 await page.getByText('Timeout: 3600s',{exact:false}).waitFor();
 const info=await page.locator('#action-confirm').boundingBox();
 assert.ok(info.height<250, 'Action info should stay compact');
 assert.equal(await page.locator('link[rel=icon]').getAttribute('href'),'/static/favicon.svg');
 await page.getByRole('button',{name:'Edit Connection test',exact:true}).click();
 assert.equal(await page.locator('#action-confirm').isVisible(),false);
 assert.equal(await page.locator('#action-editor').isVisible(),true);
 await page.getByRole('button',{name:'Information about Connection test',exact:true}).click();
 assert.equal(await page.locator('#action-editor').isVisible(),false);
 assert.equal(await page.locator('#action-confirm').isVisible(),true);
 await page.getByRole('button',{name:'Close action details',exact:true}).click();
 assert.equal(await page.locator('#action-confirm').isVisible(),false);
 await page.getByRole('button',{name:'Close client details',exact:true}).click();
 assert.equal(await page.locator('#workspace').isVisible(),false);
 assert.equal(await page.locator('.server.selected').count(),0);
 assert.equal(await page.locator('.server[aria-pressed="true"]').count(),0);
 await page.waitForTimeout(5500);
 assert.equal(await page.locator('#workspace').isVisible(),false);
 assert.equal(await page.locator('.server.selected').count(),0);
 await page.locator('.server').first().click();
 await page.getByRole('button',{name:'Connection test',exact:true}).waitFor();
 assert.equal(await page.locator('#workspace').isVisible(),true);
 assert.equal(await page.locator('.server.selected').count(),1);
 await page.getByRole('button',{name:'Connection test',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#output').textContent.includes('connected successfully'));
 await page.waitForFunction(()=>document.querySelector('#job-detail').textContent.includes('succeeded'));
 await page.getByRole('tab',{name:'Recent actions',exact:true}).click();
 await page.getByLabel('Saved action runs').waitFor();
 const firstRun=await page.locator('#job-history option').nth(1).getAttribute('value');
 await page.getByLabel('Saved action runs').selectOption(firstRun);
 await page.waitForFunction(()=>document.querySelector('#history-output').textContent.includes('connected successfully'));
 assert.equal(await page.getByRole('tab',{name:'Recent actions',exact:true}).getAttribute('aria-selected'),'true');
 // Start a different, slower request while viewing the old run.
 await page.getByRole('button',{name:'Edit Connection test',exact:true}).click();
 await page.locator('#action-editor textarea[name="command"]').fill('printf second-start; sleep 2; printf second-finish');
 await page.getByRole('button',{name:'Save action',exact:true}).click();
 await page.getByRole('button',{name:'Connection test',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#quick-tab').getAttribute('aria-selected')==='true');
 await page.getByRole('tab',{name:'Recent actions',exact:true}).click();
 await page.getByLabel('Saved action runs').selectOption(firstRun);
 await page.waitForFunction(()=>document.querySelector('#output').textContent.includes('second-finish'));
 assert.equal(await page.getByRole('tab',{name:'Recent actions',exact:true}).getAttribute('aria-selected'),'true');
 assert.match(await page.locator('#history-output').textContent(),/connected successfully/);
 await page.getByRole('tab',{name:'Quick output',exact:true}).click();
 assert.match(await page.locator('#output').textContent(),/second-finish/);
 await page.screenshot({path:'/tmp/orca-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'+ Add shortcut',exact:true}).click();
 const grid=await page.locator('#shortcuts').boundingBox(),mobileForm=await page.locator('#shortcut-editor').boundingBox();
 assert.ok(mobileForm.y+mobileForm.height<=grid.y);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'/tmp/orca-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Shared view',exact:true}).click();
 await page.getByRole('heading',{name:'Your home base'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Private link'}).count(),0);
 assert.equal(await page.locator('#fleet-summary').isVisible(),false);
 assert.equal(await page.locator('#workspace').isVisible(),false);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByRole('button',{name:'Admin login',exact:true}).waitFor();
 await page.reload();
 await page.getByRole('link',{name:'Shared link'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Private link'}).count(),0);
 const clientPage=await browser.newPage();
 await clientPage.goto('http://127.0.0.1:'+(process.env.ORCA_PREVIEW_CLIENT_PORT || '8766'));
 await clientPage.getByRole('button',{name:'Admin login',exact:true}).click();
 await clientPage.getByLabel('Password',{exact:true}).fill('orca-preview-local');
 await clientPage.getByRole('button',{name:'Sign in',exact:true}).click();
 await clientPage.getByRole('button',{name:'Show client details',exact:true}).waitFor();
 assert.equal(await clientPage.locator('#workspace').isVisible(),false);
 await clientPage.getByRole('button',{name:'Show client details',exact:true}).click();
 await clientPage.getByRole('button',{name:'Connection test',exact:true}).waitFor();
 assert.equal(await clientPage.locator('#output').textContent(),'Run an action to view its output.');
 await clientPage.getByRole('tab',{name:'Recent actions',exact:true}).click();
 await clientPage.getByLabel('Saved action runs').selectOption(firstRun);
 await clientPage.waitForFunction(()=>document.querySelector('#history-output').textContent.includes('connected successfully'));
 assert.equal(await clientPage.getByRole('tab',{name:'Recent actions',exact:true}).getAttribute('aria-selected'),'true');
 assert.equal(await clientPage.getByText('Output is saved on this client.',{exact:true}).count(),0);
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('Browser passed: login, independent client, real command output, persistence, private shortcuts, forms, and mobile layout.');
})().catch(e=>{console.error(e);process.exit(1)});
