const {chromium}=require(process.env.ORCA_PLAYWRIGHT || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.ORCA_BROWSER||undefined});
 const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:'+(process.env.ORCA_PREVIEW_PORT||'8875'));
 await page.getByRole('button',{name:'Admin login',exact:true}).click();
 await page.getByLabel('Password',{exact:true}).fill('orca-preview-local');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('button',{name:/Local test client.*Online/}).click();
 await page.getByRole('heading',{name:'Orca actions',exact:true}).waitFor();
 assert.equal(await page.locator('#orca-actions [data-edit-action]').count(),0);
 await page.locator('#orca-actions .drag-handle').waitFor();
 assert.equal(await page.locator('#orca-actions .drag-handle').count(),1);
 // Give Defined actions a card so both grids can be measured at the same viewport.
 await page.getByRole('button',{name:'+ Add action',exact:true}).click();
 await page.locator('#action-editor input[name="name"]').fill('Layout check');
 await page.locator('#action-editor textarea[name="command"]').fill('printf harmless');
 await page.getByRole('button',{name:'Save action',exact:true}).click();
 await page.getByRole('button',{name:'Layout check',exact:true}).waitFor();
 const orcaCard=await page.locator('#orca-actions .action-shell').first().boundingBox();
 const definedCard=await page.locator('#actions .action-shell').first().boundingBox();
 assert.ok(Math.abs(orcaCard.width-definedCard.width)<1);
 assert.ok(Math.abs(orcaCard.height-definedCard.height)<1);
 const heading=await page.locator('.defined-actions-heading h3').boundingBox();
 const addButton=await page.locator('#add-action').boundingBox();
 assert.ok(Math.abs(heading.y-addButton.y)<1);
 await page.locator('#orca-actions .drag-handle').press('ArrowLeft');
 assert.equal(await page.locator('#job-detail').isVisible(),false);
 await page.getByRole('button',{name:'Check image updates',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#job-detail').textContent.includes('succeeded'));
 assert.match(await page.locator('#output').textContent(),/immich-server.*UPDATE AVAILABLE/);
 await page.getByRole('tab',{name:'Docker',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('#docker-rows tr').length===7);
 assert.equal(await page.locator('#docker-rows tr').count(),7);
 assert.equal(await page.getByRole('button',{name:'Update immich-server',exact:true}).getAttribute('class').then(v=>v.includes('update-available')),true);
 assert.equal(await page.getByRole('button',{name:'Update immich-redis',exact:true}).getAttribute('class').then(v=>v.includes('update-available')),false);
 assert.equal(await page.getByRole('button',{name:'Update backup',exact:true}).isDisabled(),true);
 assert.equal(await page.getByRole('button',{name:'Start backup',exact:true}).isEnabled(),true);
 assert.equal(await page.getByRole('button',{name:'Pause backup',exact:true}).isDisabled(),true);
 assert.equal(await page.getByRole('button',{name:'Resume worker',exact:true}).isEnabled(),true);
 assert.equal(await page.getByRole('button',{name:'Stop worker',exact:true}).isDisabled(),true);
 const dot=page.getByRole('button',{name:'Running · Healthy',exact:true});await dot.focus();
 assert.equal(await dot.locator('..').getByRole('tooltip').isVisible(),true);
 await page.screenshot({path:'/tmp/orca-docker-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Edit update command for immich-redis',exact:true}).click();
 await page.getByLabel('Working directory',{exact:true}).fill('/tmp');
 await page.getByLabel('Update command',{exact:true}).fill('printf "updating project\\n"; sleep 2; printf "project complete\\n"');
 await page.getByRole('button',{name:'Save update command',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('#docker-dialog').open);
 await page.getByRole('button',{name:'Update immich-server',exact:true}).click();
 await page.getByRole('button',{name:'Run update',exact:true}).waitFor();
 assert.match(await page.locator('#docker-dialog').textContent(),/Multiple containers may be recreated and stopped services may start/);
 assert.match(await page.locator('#docker-dialog').textContent(),/printf "updating project/);
 await page.screenshot({path:'/tmp/orca-docker-confirm.png',fullPage:true});
 await page.getByRole('button',{name:'Run update',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#docker-progress-status')?.textContent.includes('running'));
 assert.equal(await page.getByRole('tab',{name:'Docker',exact:true}).getAttribute('aria-selected'),'true');
 assert.equal(await page.getByRole('button',{name:'Stop immich-redis',exact:true}).isDisabled(),true);
 await page.waitForFunction(()=>document.querySelector('#docker-progress-status')?.textContent==='Update command completed.');
 assert.match(await page.locator('#docker-progress-output').textContent(),/project complete/);
 assert.match(await page.locator('#docker-dialog-body').textContent(),/View this run result in Recent actions/);
 assert.doesNotMatch(await page.locator('#output').textContent(),/updating project|project complete/);
 await page.getByRole('button',{name:'Close Docker dialog',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('[aria-label="Update immich-server"]').classList.contains('update-available'));
 // The shared manual recipe survives the fixture's container recreation.
 await page.getByRole('button',{name:'Edit update command for immich-server',exact:true}).click();
 assert.match(await page.getByLabel('Update command',{exact:true}).inputValue(),/project complete/);
 await page.getByRole('button',{name:'Close Docker dialog',exact:true}).click();
 await page.getByRole('button',{name:'Start backup',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[aria-label="Stop backup"]') && !document.querySelector('[aria-label="Stop backup"]').disabled);
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'/tmp/orca-docker-mobile.png',fullPage:true});
 await page.getByRole('tab',{name:'Actions',exact:true}).click();
 assert.match(await page.locator('#output').textContent(),/Simulated container control/);
 await page.getByRole('tab',{name:'Recent actions',exact:true}).click();
 const updateOption=page.locator('#job-history option').filter({hasText:'Update immich'}).first();
 await page.locator('#job-history').selectOption(await updateOption.getAttribute('value'));
 await page.waitForFunction(()=>document.querySelector('#history-output').textContent.includes('project complete'));
 // Discovery failure replaces stale healthy rows with an error.
 await page.route('**/remote/docker',route=>route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({error:'Docker access unavailable'})}));
 await page.getByRole('tab',{name:'Docker',exact:true}).click();
 await page.getByText('Docker access unavailable',{exact:true}).waitFor();
 assert.equal(await page.locator('#docker-rows tr').count(),0);
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Docker browser passed: tabs, row indicators, shared recipes, confirmation, progress, job limit, recreation, lifecycle, history, mobile, and failures.');
})().catch(error=>{console.error(error);process.exit(1)});
